# Generated by Django 3.0 on 2020-03-28 12:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tajniacy', '0002_auto_20200327_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
