# Generated by Django 3.0 on 2020-04-05 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tajniacy', '0005_auto_20200329_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='uncovered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
